services:
  muse:
    image: ghcr.io/museofficial/muse:latest
    restart: always
    volumes:
      - ./muse:/data
    environment:
      - DISCORD_TOKEN=DISCORD_TOKEN_PLACEHOLDER
      - YOUTUBE_API_KEY=YOUTUBE_API_KEY_PLACEHOLDER
      - SPOTIFY_CLIENT_ID=SPOTIFY_CLIENT_ID_PLACEHOLDER
      - SPOTIFY_CLIENT_SECRET=SPOTIFY_CLIENT_SECRET_PLACEHOLDER
    network_mode: "service:warp"
    depends_on:
      - warp
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    ports:
      - "1080:1080"
    environment:
      - WARP_SLEEP=2
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp
